apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuditBenchmark
  template:
    metadata:
      labels:
        app: AuditBenchmark
    spec:
      containers:
      - name: benchmarkrepos
        image: samplecr.azurecr.io/benchmarkrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: benchmark
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuditBenchmark